spring:
  profiles:
    active: eureka

---
spring:
  profiles: eureka
  cloud:
    zookeeper:
      enabled: false


server:
  port: 8882
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
