server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blueJoy/spring-cloud-example-2x/config-repo
          #skip-ssl-validation: true
          timeout: 4 # 超时默认秒